import {
  loadCatalog,
  type ModelCatalog,
  type ModelCatalogEntry,
  type ModelProvider,
} from "@seri/model-catalog";
import { hasCodexSubscription } from "../auth/codexAuthStore";
import { type CodexListedModel, listCodexModels } from "../auth/codexRefresh";
import { hasXaiSubscription, loadXaiSubscription } from "../auth/xaiAuthStore";
import { xaiAuthedFetch } from "../auth/xaiRefresh";
import { printWarning } from "../cli/output";
import bundledManifest from "./catalog-manifest.json";
import { grokCatalogHeaders, grokProxyBaseUrl } from "./xai";

// The CLI's own copy of @seri/model-catalog's fallback manifest (generated by
// packages/model-catalog/src/generate.ts, committed here rather than fetched at runtime). A
// plain .json import, unlike rg-vendored.bin's raw binary asset (vendorRipgrep.ts): bun's
// bundler already treats a JSON import as a module and inlines it at build time, so it needs no
// `with { type: "file" }` to survive inside the compiled binary.
const FALLBACK_MANIFEST = bundledManifest as ModelCatalog;

// Per-provider, not whole-catalog: a live models.dev payload can carry zero rows for one
// configured provider while another configured provider's live rows are fine. Scoped to
// `configured` (not every provider FALLBACK_MANIFEST has rows for): the guided picker
// (tui/commands.ts's decideGuidedModelPickerOpen) filters to the same `configured` set, so an
// unconfigured provider's backfilled rows would never be shown — but they'd still join that
// provider's route groups and inflate the `alternatives`/ordering the SHOWN rows report, for
// providers the picker has no reason to know about at all.
export function catalogWithFallback(
  live: ModelCatalog,
  configured: ReadonlySet<ModelProvider>,
): ModelCatalog {
  const liveProviders = new Set(live.entries.map((entry) => entry.provider));
  const backfill = FALLBACK_MANIFEST.entries.filter(
    (entry) => configured.has(entry.provider) && !liveProviders.has(entry.provider),
  );
  return backfill.length === 0 ? live : { ...live, entries: [...live.entries, ...backfill] };
}

// Warns at most once per process (code-review finding, PR #91 round 3): `run()` and
// `prepareSession` both call `getModelCatalog()` independently on the same guided-setup run, and
// `loadCatalog`'s own promise cache dedupes the FETCH across both calls, but each caller used to
// still do its own `catalog === FALLBACK_MANIFEST` check and print its own warning — one failed
// fetch, two identical lines. A plain boolean, not a promise-identity check: `loadCatalog` is
// itself declared `async function`, so every call returns a freshly wrapped Promise even when it
// resolves the SAME cached inner promise — the outer promise's own identity can't distinguish "the
// same fetch" from "a different call".
let warnedFallback = false;

// Test-only reset, mirroring `resetCatalogCache`'s own contract (@seri/model-catalog): a test that
// exercises the fetch-fails-and-falls-back path more than once in the same `bun test` process needs
// to clear this alongside that cache, or only the first call in the whole process would ever warn.
export function resetFallbackWarning(): void {
  warnedFallback = false;
}

// Starts the models.dev fetch without waiting for it, so it overlaps whatever the user is doing on
// the welcome splash instead of being paid for after they dismiss it. `loadCatalog` caches the
// in-flight promise, so the real `getModelCatalog` await further into startup joins THIS fetch
// rather than starting a second one. Deliberately not `getModelCatalog`: this call has no sink to
// print through (it runs before the renderer exists), and routing the fallback warning to a bare
// `console.error` here would write straight onto the alt-screen buffer. Leaving the warning to the
// awaited call, which has a sink, keeps it on screen where the user can read it.
export function prewarmModelCatalog(): void {
  // `loadCatalog` resolves to the bundled manifest on any failure and never rejects (its own
  // contract), so an unawaited call here cannot become an unhandled rejection.
  void loadCatalog(FALLBACK_MANIFEST, fetch);
}

// The one dispatch point apps/cli calls to get the model catalog: @seri/model-catalog does the
// fetch-with-fallback and the in-memory caching, this just supplies the CLI's own bundled
// fallback and warns once when that fallback is what actually got used.
export async function getModelCatalog(
  fetchFn: typeof fetch = fetch,
  // Forwarded to printWarning's own `sink` param — prepareSession's TUI path (cli.ts) passes its
  // preMountMessages queue here for the identical reason it passes one to loadGrants/
  // printPreApproved: this call happens after enterAltScreen() but before the TUI's own Ink mount,
  // so the default console.error would land on the alt-screen buffer and vanish. The OTHER call
  // site (run()'s unawaited guided-setup gate) omits this and stays on the default — that one runs
  // while an Ink instance IS mounted, so `patchConsole: true` already routes it safely.
  sink?: (line: string) => void,
  configDir?: string,
): Promise<ModelCatalog> {
  const catalog = await loadCatalog(FALLBACK_MANIFEST, fetchFn);
  if (catalog === FALLBACK_MANIFEST && !warnedFallback) {
    warnedFallback = true;
    // `loadCatalog` returns the manifest for two different reasons and the user deserves the right
    // one: a genuinely unreachable models.dev, and this flag, where nothing was tried at all. Reading the env var here rather than having `loadCatalog` report which branch it took
    // keeps the flag's meaning in the app that documents it.
    printWarning(
      process.env.SERI_DISABLE_MODELS_FETCH
        ? "models.dev fetch disabled by SERI_DISABLE_MODELS_FETCH; using the bundled model catalog"
        : "could not reach models.dev; using the bundled model catalog",
      sink,
    );
  }
  let merged = catalog;
  if (configDir !== undefined && hasXaiSubscription(configDir)) {
    merged = await mergeGrokSubscriptionModels(merged, configDir, fetchFn);
  }
  return withCodexSubscriptionCatalog(merged);
}

const CODEX_DEFAULT_CONTEXT = 272_000;
const CODEX_DEFAULT_OUTPUT = 16_384;

export function overlayCodexModels(
  catalog: ModelCatalog,
  models: readonly CodexListedModel[],
): ModelCatalog {
  if (models.length === 0) return catalog;
  const existingById = new Map(
    catalog.entries
      .filter((entry) => entry.provider === "openai")
      .map((entry) => [entry.id, entry]),
  );
  const openai: ModelCatalogEntry[] = models.map((model) => {
    const existing = existingById.get(model.id);
    const reasoningValues = model.supportedReasoningEfforts;
    return {
      id: model.id,
      provider: "openai",
      displayName: model.displayName,
      family: existing?.family ?? null,
      contextWindow: existing?.contextWindow ?? CODEX_DEFAULT_CONTEXT,
      maxOutputTokens: existing?.maxOutputTokens ?? CODEX_DEFAULT_OUTPUT,
      toolCall: existing?.toolCall ?? true,
      reasoning: reasoningValues.length > 0 || (existing?.reasoning ?? false),
      reasoningOptions:
        reasoningValues.length > 0
          ? [{ type: "effort", values: reasoningValues }]
          : existing?.reasoningOptions,
      pricing: undefined,
    };
  });
  return {
    ...catalog,
    entries: [...catalog.entries.filter((entry) => entry.provider !== "openai"), ...openai],
  };
}

export async function withCodexSubscriptionCatalog(catalog: ModelCatalog): Promise<ModelCatalog> {
  if (!hasCodexSubscription()) return catalog;
  try {
    return overlayCodexModels(catalog, await listCodexModels());
  } catch {
    return catalog;
  }
}

function stubGrokEntry(id: string): ModelCatalogEntry {
  return {
    id,
    provider: "xai",
    displayName: id,
    family: "grok",
    contextWindow: 131072,
    maxOutputTokens: 16384,
    toolCall: true,
    reasoning: true,
    pricing: undefined,
  };
}

export function idsFromGrokModelsPayload(body: unknown): string[] {
  if (Array.isArray(body)) {
    return body.filter((item): item is string => typeof item === "string" && item.length > 0);
  }
  if (body === null || typeof body !== "object") return [];
  const record = body as Record<string, unknown>;
  const list = record.data ?? record.models;
  if (!Array.isArray(list)) return [];
  const ids: string[] = [];
  for (const item of list) {
    if (typeof item === "string" && item.length > 0) ids.push(item);
    else if (
      item !== null &&
      typeof item === "object" &&
      typeof (item as { id?: unknown }).id === "string" &&
      (item as { id: string }).id.length > 0
    ) {
      ids.push((item as { id: string }).id);
    }
  }
  return ids;
}

export function mergeGrokSubscriptionCatalog(
  catalog: ModelCatalog,
  proxyIds: string[],
): ModelCatalog {
  if (proxyIds.length === 0) return catalog;
  const existing = new Map(
    catalog.entries.filter((entry) => entry.provider === "xai").map((entry) => [entry.id, entry]),
  );
  const xaiEntries = proxyIds.map((id) => existing.get(id) ?? stubGrokEntry(id));
  return {
    ...catalog,
    entries: [...catalog.entries.filter((entry) => entry.provider !== "xai"), ...xaiEntries],
  };
}

async function mergeGrokSubscriptionModels(
  catalog: ModelCatalog,
  configDir: string,
  fetchFn: typeof fetch,
): Promise<ModelCatalog> {
  try {
    const authed = xaiAuthedFetch(configDir, fetchFn);
    const accountId = loadXaiSubscription(configDir)?.accountId;
    const response = await authed(`${grokProxyBaseUrl(configDir)}/models`, {
      headers: grokCatalogHeaders(accountId),
    });
    if (!response.ok) return catalog;
    const body: unknown = JSON.parse(await response.text());
    return mergeGrokSubscriptionCatalog(catalog, idsFromGrokModelsPayload(body));
  } catch {
    return catalog;
  }
}
